/** Declaration file generated by dts-gen */

// vue-cookie-law does not contain typings, so let's supply our own

import Vue from 'vue'

declare module 'vue/types/vue' {
    // 3. Declare augmentation for Vue
    interface Vue {
        props: {
            buttonClass: {
                default: string;
                type: any;
            };
            buttonLink: {
                type: any;
            };
            buttonLinkText: {
                default: string;
                type: any;
            };
            buttonText: {
                default: string;
                type: any;
            };
            message: {
                default: string;
                type: any;
            };
            position: {
                default: string;
                type: any;
            };
            theme: {
                default: string;
                type: any;
            };
            transitionName: {
                default: string;
                type: any;
            };
        };
        
        computed: {
            containerPosition(): any;
            cookieTheme(): any;
        };

        methods: {
            accept(): any;
            getVisited(): void;
            setVisited(): any;
        }
    }
}